[versions]
csv = "1.14.1"
exposed = "1.0.0-rc-4"
h2 = "2.4.240"
logback = "1.5.22"
kotest = "5.9.1"

[libraries]
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "csv" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
